### ISSUE TITLE
Bug na hora de iniciar o script

### ISSUE THREAD

**Issue by brlouco** [grenoxx/LordPhish#3]
![error](https://user-images.githubusercontent.com/73054413/108717784-721cc200-74fc-11eb-973a-5b8d668b905b.png)
Assim que executa bash lord.sh e espera pelo input, a linguagem muda.

**Comment by brlouco** [comment]
Encontrei o erro, na linha do read, removendo o caractere de escape \en resolve o problema.

**Comment by graysuit** [comment]
@brlouco 
I guess, problem exists in linux only.
In windows it looks fine.
```
[99] Custom         [Y] Youtube channel   [T] Telegram Group
[00] Exit           [F] Follow me one git hub
 [~] Select an option: asdasd
```
You mean change this line:
`read -p $' \e[1;31m[\e[0m\e[1;77m~\e[0m\e[1;31m]\e[0m\e[1;92m Select an option: \e[0m\e[1;96m\en' menu_option`
to
`read -p $' \e[1;31m[\e[0m\e[1;77m~\e[0m\e[1;31m]\e[0m\e[1;92m Select an option: \e[0m\e[1;96m\e' menu_option`
?
https://github.com/grenoxx/LordPhish/blob/main/lord.sh#L204

**Comment by grenoxx** [comment]
> Encontrei o erro, na linha do read, removendo o caractere de escape \en resolve o problema.

Acabei de mudar a linha de codigo, atualize e me de um retorno

**Comment by brlouco** [comment]
![image](https://user-images.githubusercontent.com/73054413/108776332-0ad53100-7541-11eb-8d38-659ca085a870.png)

**Comment by brlouco** [comment]
![image](https://user-images.githubusercontent.com/73054413/109215552-10758580-7792-11eb-8641-0fb0c0bdafc0.png)
Tem que atualizar todas as linhas de código que recebe input
