### ISSUE TITLE
Give Credit to AdvPhishing

### ISSUE THREAD

**Issue by Ignitetch** [grenoxx/LordPhish#5]
You need to give credit advphishing tool as you have copied multiple files and code as well.

Thanks 
Secnhack Team

**Comment by swagkarna** [comment]
> You need to give credit advphishing tool as you have copied multiple files and code as well.
> 
> Thanks
> Secnhack Team

Bro is this your site https://secnhack.in/

**Comment by graysuit** [comment]
@Ignitetch 
Can you show us the name of files, that were copied ?
so that we can verify...

**Comment by swagkarna** [comment]
go and check is whatapp opt bypass tool

**Comment by graysuit** [comment]
@grenoxx 

Your some files are using `Ignitetch/AdvPhishing`.
You can resolve conflict by just adding credit and a backlink that I already done in this PR.
```
https://github.com/grenoxx/LordPhish/blob/main/.sites/whatsapp/otp.login.php
https://github.com/Ignitetch/AdvPhishing/blob/master/sites/whatsapp-phishing/otp.login.php
```

**Comment by graysuit** [comment]
@Ignitetch 
Your repo so popular, but even why it don't have any LICENSE file which specify who can use,modify,copy,warranty etc ?

**Comment by Ignitetch** [comment]
Thanks All of you gys for your great response :P !!

I want to do just give credit to us on main web page and that's it 👍

**Comment by Ignitetch** [comment]
==

> > You need to give credit advphishing tool as you have copied multiple files and code as well.
> > Thanks
> > Secnhack Team
> 
> Bro is this your site https://secnhack.in/

yes 👍

**Comment by grenoxx** [comment]
> You need to give credit advphishing tool as you have copied multiple files and code as well.
> 
> Thanks 
> Secnhack Team

Credit one bash file bro, This above the license! and thanks for alerting, I must have forgotten to add the credits to you, because I added almost everyone's credit !!

**Comment by grenoxx** [comment]
> ==
> 
> > > You need to give credit advphishing tool as you have copied multiple files and code as well.
> > > Thanks
> > > Secnhack Team
> > 
> > Bro is this your site https://secnhack.in/
> 
> yes 👍 

And again I'm sorry for the inconvenience
